apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontendpod
    type: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
  nodeSelector:
    size: large
    
