apiVersion: v1
kind: Replicaset
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp
    labels:
      name: myapp
      type: frontend
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: frontend